language: ruby
rvm:
  - 2.0.0
  - 2.1.1
env:
  - POSTGIS=2.0
gemfile:
  - travis/ar41.gemfile
matrix:
  exclude:
before_install: ./travis/before_install.sh
before_script: ./travis/before_script.sh
script: bundle exec rake test
